apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef:
    chartVersion: 5.9.18
  clusterSpec:
    statefulset:
      initContainers:
        setDataDirOwnership:
          enabled: true
    storage:
      persistentVolume:
        enabled: true
        size: "10Gi"
        storageClass: "openebs-hostpath"