storage:
  persistentVolume:
    enabled: true
    size: "10Gi"
    storageClass: "openebs-hostpath" # Customized for my Talos Linux cluster

resources:
  cpu:
    cores: 2 # Redpanda makes use of a thread per core model. For this reason, Redpanda should only be given full cores.
  memory:
    enable_memory_locking: true
    container:
      max: "5Gi" # Set to 2.5x the amount of full CPU Cores

statefulset:
  replicas: 3
  initContainers:
    setDataDirOwnership:
      enabled: true
      
external:
  enabled: true
  type: LoadBalancer
  externalDns:
    enabled: true