storage:
  persistentVolume:
    enabled: true
    size: "10Gi"
    storageClass: "openebs-hostpath" # Customized for my Talos Linux cluster

resources:
  cpu:
    cores: 1 # Redpanda makes use of a thread per core model. For this reason, Redpanda should only be given full cores.
  memory:
    container:
      max: "2.5Gi" # Set to 2.5x the amount of full CPU Cores

statefulset:
  replicas: 3
  initContainers:
    setDataDirOwnership:
      enabled: true